spring.application.name=VVServer
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=${VV_CERT_STORE}
server.ssl.key-store-password=${VV_CERT_PASS}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=${VV_KEY_ALIAS}
